name: Update My Custom List
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Скачиваем всю историю, чтобы не было конфликтов

      - name: Download and Combine
        run: |
          # Скачиваем списки (ваши ссылки)
          curl -s https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-raw.lst > combined.txt
          echo "" >> combined.txt
          curl -s https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/discord.lst >> combined.txt
          echo "" >> combined.txt
          curl -s https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/google_ai.lst >> combined.txt
          echo "" >> combined.txt
          curl -s https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/telegram.lst >> combined.txt
          echo "" >> combined.txt
          curl -s https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Services/youtube.lst >> combined.txt

          # Чистим и сортируем
          sed -i '/^$/d' combined.txt
          sort -u combined.txt -o combined.txt

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-update list
          file_pattern: 'combined.txt'
          push_options: '--force' # Если и это не поможет, значит дело в защите ветки
          skip_fetch: false